#!/bin/bash

echo '--------------------------------------------------'
echo '|                 Config Install                  |'
echo '--------------------------------------------------'

#Замените на своё:
username=neo
hostname=matrix
pass=1811
disk_root=/dev/nvme0n1p5
disk_boot=/dev/nvme0n1p1
sleep=5

echo '--------------------------------------------------'
echo '|Install Arch Linux '$username'@'hostname'       |'
echo '--------------------------------------------------'
pacman -Sy sed wget --noconfirm
#fonts:
setfont cyr-sun16
#echo:
echo 'KEYMAP=ru' >> /etc/vconsole.conf
#echo:
echo 'FONT=cyr-sun16' >> /etc/vconsole.conf
#timezone:
ln -sf /usr/share/zoneinfo/Asia/Krasnoyarsk /etc/localetime
#services:
systemctl enable iwd.service
#services:
systemctl enable NetworkManager.service
#mount boot:
mount $disk_boot /boot/efi
#hostname:
echo $hostname >> /etc/hostname
#locale eng:
sed -i 's|#en_US.UTF-8 UTF-8|en_US.UTF-8 UTF-8|g' /etc/locale.gen
#locale rus:
sed -i 's|#ru_RU.UTF-8 UTF-8|ru_RU.UTF-8 UTF-8|g' /etc/locale.gen
#locale generation:
locale-gen
#locale conf:
echo 'LANG=en_US.UTF-8' >> /etc/locale.conf
#locale conf:
echo 'LANG=ru_RU.UTF-8' >> /etc/locale.conf
#passwd root:
(
    echo $pass
    echo $pass
) | passwd
#add user:
useradd -m -g users -G wheel,video -s /bin/bash $username
#passwd user:
(
    echo $pass
    echo $pass
) | passwd $username
#pacman.conf:
sed 's|#ParallelDownloads = 5|ParallelDownloads = 5|g' -i /etc/pacman.conf
#pacman.conf:
sed 's|#[multilib]\#nInclude = /etc/pacman.d/mirrorlist|[multilib]\nInclude = /etc/pacman.d/mirrorlist|g' -i /etc/pacman.conf
#install core lqx:
pacman-key --keyserver hkps://keyserver.ubuntu.com --recv-keys 9AE4078033F8024D
#install core lqx:
pacman-key --lsign-key 9AE4078033F8024D
#install core lqx:
echo '[liquorix]' >> /etc/pacman.conf
#install core lqx:
echo 'Server = https://liquorix.net/archlinux/$repo/$arch' >> /etc/pacman.conf
#pacman -Sy:
pacman -Sy
#install core lqx:
pacman -S linux-lqx linux-lqx-headers --noconfirm
#sudoers:
#без запроса пароля:
#sed 's|# %wheel ALL=(ALL:ALL) NOPASSWD: ALL|%wheel ALL=(ALL:ALL) NOPASSWD: ALL|g' -i /etc/sudoers
#с запросом пароля:
sed 's|# %wheel ALL=(ALL:ALL) ALL|%wheel ALL=(ALL:ALL) ALL|g' -i /etc/sudoers
#chown:
#chown -R $username:users /home/$username/
#blkid:
uuid=$(blkid -s UUID -o value $disk_root)
#раскомментируйте необходимое:
#refind nvidia:
#echo '"Boot to standard options" "rw root=UUID='$uuid' rootflags=subvol=@ loglevel=0 quiet splash rootfstype=btrfs nvidia-drm.modeset=1"' >> /boot/refind_linux.conf
#refind nvidia:
#echo '"Boot to single-user mode" "rw root=UUID='$uuid' rootflags=subvol=@ loglevel=0 quiet splash rootfstype=btrfs nvidia-drm.modeset=1 single"' >> /boot/refind_linux.conf
#refind mesa:
echo '"Boot to standard options" "rw root=UUID='$uuid' rootflags=subvol=@ loglevel=0 quiet splash rootfstype=btrfs"' >> /boot/refind_linux.conf
#refind mesa:
echo '"Boot to single-user mode" "rw root=UUID='$uuid' rootflags=subvol=@ loglevel=0 quiet splash rootfstype=btrfs single"' >> /boot/refind_linux.conf
#refind:
echo '"Boot with minimal options ro root='$disk_root'"' >> /boot/refind_linux.conf
#refind:
refind-install
sleep $sleep
echo '--------------------------------------------------------------------------------'
echo '|                    Установка пользовательских приложений                     |'
echo '--------------------------------------------------------------------------------'
#echo "$username:$pass" | chpasswd && sh "/home/$username/install3.sh" $username $pass
#exit:
exit
