#!/bin/bash

echo '--------------------------------------------------'
echo '|                Config Install                  |'
echo '--------------------------------------------------'

#Измените на своё:
username=neo
hostname=matrix
pass=1811
disk_root=/dev/nvme0n1p5
disk_boot=/dev/nvme0n1p1
#Раскомментируйте необходимое:
disk_swap=/dev/nvme0n1p6
#ucode=amd-ucode
ucode=intel-ucode
sleep=5

#setfont cyr-sun16:
setfont cyr-sun16
echo '--------------------------------------------------'
echo '|              Install Arch Linux                |'
echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname'		'
echo '--------------------------------------------------'

echo '--------------------------------------------------'
echo '|             Подготовка диска                   |'
echo '--------------------------------------------------'
echo '            '$disk_root'@'$disk_boot'				      '
echo '--------------------------------------------------'
echo '--------------------------------------------------'
echo '|             Монтирование разделов               |'
echo '--------------------------------------------------'
#mount disk:
mount -o rw,noatime,compress=lzo,recovery,autodefrag,space_cache=v2,ssd,discard=async,subvol=@ $disk_root /mnt
#mkdir folders:
mkdir /mnt/{var,home,boot}
#mkdir /boot/efi:
mkdir /mnt/boot/efi
#mount disk:
mount -o rw,noatime,compress=lzo,recovery,autodefrag,space_cache=v2,ssd,discard=async,subvol=@home $disk_root /mnt/home
#mount disk:
mount -o rw,noatime,compress=lzo,recovery,autodefrag,space_cache=v2,ssd,discard=async,subvol=@var $disk_root /mnt/var
#sleep:
sleep $sleep
#sleep:
#раскомментируйте необходимое:
#chroot nvidia:
cp -f arch-install-btrfs/mount_disk /mnt/home/$username/
cp -f arch-install-btrfs/mount_disk2 /mnt/home/$username/
#sleep:
#sleep $sleep
#раскомментируйте необходимое:
#chroot /mnt:
#arch-chroot /mnt /bin/bash -c "$(cat /mnt/home/$username/mount_disk2)" $username $hostname $pass
#переход в chroot и окончание скрипта:
arch-chroot /mnt
#sleep:
#sleep $sleep
#echo '--------------------------------------------------'
#echo '|                 Перезагрузка                   |'
#echo '--------------------------------------------------'
umount -R /mnt/
reboot
