#!/bin/bash

echo '--------------------------------------------------'
echo '|                Config Install                  |'
echo '--------------------------------------------------'

#Измените на своё:
username=neo
hostname=matrix
pass=1811
disk_root=/dev/sdX
disk_boot=/dev/sdX
flash=/dev/sdX
#Раскомментируйте необходимое:
disk_swap=/dev/sdX
#ucode=amd-ucode
ucode=intel-ucode
sleep=5

#setfont cyr-sun16:
setfont cyr-sun16
echo '--------------------------------------------------'
echo '|              Install Arch Linux                |'
echo '--------------------------------------------------'
echo 'Install Arch Linux '$username'@'$hostname'		'
echo '--------------------------------------------------'

echo '--------------------------------------------------'
echo '|             Подготовка диска                   |'
echo '--------------------------------------------------'
echo '            '$disk_root'@'$disk_boot'				      '
echo '--------------------------------------------------'
#sleep:
sleep $sleep

echo '--------------------------------------------------'
echo '|             Разметка диска                     |'
echo '--------------------------------------------------'
#sleep:
sleep $sleep
#formating disk:
mkfs.btrfs -f $disk_root
#formating disk:
mkfs.vfat $disk_boot
#раскомментируйте необходимое:
#formatting disk:
#mkswap $disk_swap
#swapon $disk_swap
#mount mnt:
mount $disk_root /mnt
#cd /mnt:
cd /mnt
#su cr:
btrfs su cr @
#su cr:
btrfs su cr @home
#su cr:
#btrfs su cr @var
#cd:
cd
#umount:
umount /mnt
#sleep
sleep $sleep
#sleep:
echo '--------------------------------------------------'
echo '|             Монтирование разделов               |'
echo '--------------------------------------------------'
#sleep:
sleep $sleep
#mount disk: 
 mount -o rw,noatime,compress-force=zstd:3,ssd,discard,subvol=@ $disk_root /mnt
 #mkdir folders: 
 mkdir /mnt/{home,boot}
 #mkdir /boot/efi: 
 mkdir /mnt/boot/efi 
 #mount disk: 
 mount -o rw,noatime,compress-force=zstd:3,ssd,discard,subvol=@home $disk_root /mnt/home
echo '--------------------------------------------------'
echo '|             Установка Arch Linux                |'
echo '--------------------------------------------------'
#sleep:
sleep $sleep
#install arch:
pacstrap -K /mnt base base-devel linux-firmware grub refind efibootmgr iwd networkmanager micro htop btrfs-progs git ntfs-3g $ucode bash --noconfirm
#fstab generation:
genfstab -U -p /mnt >> /mnt/etc/fstab
#chroot:
mkdir -p /mnt/home/$username/
#chroot nvidia:
cp -f arch-install-btrfs/flash_install /mnt/home/$username/
cp -f arch-install-btrfs/flash_install2 /mnt/home/$username/
cp -f arch-install-btrfs/flash_install3.sh /mnt/home/$username/
#sleep:
#sleep $sleep
#раскомментируйте необходимое:
#chroot /mnt:
arch-chroot /mnt /bin/bash -c "$(cat /mnt/home/$username/flash_install2)" $username $hostname $pass
#переход в chroot и окончание скрипта:
#arch-chroot /mnt
#sleep:
#sleep $sleep
#echo '--------------------------------------------------'
#echo '|                 Перезагрузка                   |'
#echo '--------------------------------------------------'
umount -R /mnt/
reboot
